language: rust

git:
  depth: false

dist: trusty
sudo: required

cache:
  cargo: true
  timeout: 240
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/target/tmp

rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

env:
  global:
    - RUST_BACKTRACE="1"
    - RUST_FLAGS="-C debug-assertions"

script:
  - echo "skipping tests"

before_deploy:
  - if [[ "$TEST_SUITE" == "pool-p2p-src" ]]; then
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi
  - if [[ "$TEST_SUITE" == "release" ]]  && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi

deploy:
  provider: releases
  api_key:
    secure: FYa0dXm73yZQ2TWzn7N+rl11NRJid7xpOXBtJ5cPS/8Vd9by56zCwaXWjCHRTxFx5FDwsTtttCIR1/L+9TTLaOaOcnFiVDoy24YakqIF3KdCXn6q0kJVtDOWGB2OQffuxMM6taiCHvLwrv0xZm2+lo1YXobK0Lv962M5HHDVF9Zyh+SrN+LcNNTaQoJ1M9uqaDgK9EYA1ulOoQXjckBN9XX7Z7LpLU5NJQCdCIPMORrRlOvybBBeAD//jW9nlyMoCcS9J9YwTXDk0hblfpdxKtk3QBKcAbS2E+5t/B2huSD8YYVcnf77O8xrC1B91OlfknWrOv9TjgySqBnFK9c+m6iOvptQDKZsAcLNedlHzIKDglu29inpwGvXJA2btGn0tMVU9tlX3Jf5FoLWhFuUZo8bga2TyVybLUeYvdxiLDvB4eBQhjL08e2tO7LPWXTb5d6SxfDzAZi6YPKYt6tgcIxu3FmL8ipcj9ymzaxHzFZqSlSo8jqsGjK9/yrgvNKTz+PCIFREb82ClHVRm29YK0A88DfTgPEcgNqEblq3iK9KPm8akbUagzLzFBzInhvagEyqDFkCFZ3zRCWdGiBrnomyP8aGK5TId6Y23xpv+kuYbZ0Losz3yqO4bB5z0ih04/0I69ClG22wXuhW15a1gEV/jYaXymedqmxcIWmAk7o=
  file_glob: true
  file: target/release/bitgrin-*.tgz*
  skip_cleanup: true
  on:
    repo: bitgrin/bitgrin
    tags: true
