[package]
name = "bitgrin_gen_gen"
version = "0.0.1"
edition = "2018"
authors = ["BitGrin Developers <mimblewimble@lists.launchpad.net>"]
description = "Utility to automate the generation of BitGrin's genesis block"
license = "Apache-2.0"
repository = "https://github.com/bitgrin/bitgrin"
keywords = [ "crypto", "bitgrin", "mimblewimble" ]
readme = "README.md"

[[bin]]
name = "gen_gen"
path = "src/bin/gen_gen.rs"

[dependencies]
chrono = "0.4.4"
cuckoo_miner = "0.5.2"
curl = "0.4.19"
bitgrin_core = { path = "../../core" }
bitgrin_chain = { path = "../../chain" }
bitgrin_keychain = { path = "../../keychain" }
grin_miner_plugin = "0.5.2"
bitgrin_store = { path = "../../store" }
bitgrin_util = { path = "../../util" }
bitgrin_wallet = { path = "../../wallet" }
rpassword = "2.0.0"
serde_json = "1"

[patch.crates-io]
bitgrin_api = { path = "../../api" }
bitgrin_core = { path = "../../core" }
bitgrin_chain = { path = "../../chain" }
bitgrin_keychain = { path = "../../keychain" }
bitgrin_util = { path = "../../util" }
bitgrin_wallet = { path = "../../wallet" }
